cloudera_manager:
  ports: 
    - 7180
  image: docker.iwanna.xyz:5000/cm:v3
  command: '/usr/sbin/sshd -D'
master:
  image: docker.iwanna.xyz:5000/cdh:v4
  command: '/bin/bash -c "sed -i \"s/^server_host.+$/server_host={{cloudera_manager}}/g\" /etc/cloudera-scm-agent/config.ini && /usr/sbin/sshd -D"'
slave1:
  image: docker.iwanna.xyz:5000/cdh:v4
  command: '/bin/bash -c "sed -i \"s/^server_host.+$/server_host={{cloudera_manager}}/g\" /etc/cloudera-scm-agent/config.ini && /usr/sbin/sshd -D"'
slave2:
  image: docker.iwanna.xyz:5000/cdh:v4
  command: '/bin/bash -c "sed -i \"s/^server_host.+$/server_host={{cloudera_manager}}/g\" /etc/cloudera-scm-agent/config.ini && /usr/sbin/sshd -D"'
