cloudera_manager:
  ports: 
    - 7180
  image: docker.iwanna.xyz:5000/cm:v2
  command: '/usr/sbin/sshd -D'
master:
  image: docker.iwanna.xyz:5000/cdh:v2
  command: '/usr/sbin/sshd -D'
slave1:
  image: docker.iwanna.xyz:5000/cdh:v2
  command: '/usr/sbin/sshd -D'
slave2:
  image: docker.iwanna.xyz:5000/cdh:v2
  command: '/usr/sbin/sshd -D'
slave3:
  image: docker.iwanna.xyz:5000/cdh:v2
  command: '/usr/sbin/sshd -D'
